### ISSUE TITLE
Model is loading but stt not working

### ISSUE THREAD

**Issue by 0k00l** [fyhertz/rocm-wyoming-whisper#2]
Hi,

Like ins subject, i can see when model is loading by seeing amdgpu_top but when i'm tring to use whisper via hoemassistant just followed error occurs:

_Attaching to whisper
whisper  | INFO:__main__:Ready
whisper  | ERROR:asyncio:Task exception was never retrieved
whisper  | future: <Task finished name='Task-5' coro=<AsyncEventHandler.run() done, defined at /opt/conda/envs/py_3.10/lib/python3.10/site-packages/wyoming/server.py:28> exception=RuntimeError('HIP error: the operation cannot be performed in the present state\nHIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing HIP_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_HIP_DSA` to enable device-side assertions.\n')>
whisper  | Traceback (most recent call last):
whisper  |   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/wyoming/server.py", line 35, in run
whisper  |     if not (await self.handle_event(event)):
whisper  |   File "/src/wyoming_whisper/handler.py", line 73, in handle_event
whisper  |     response = self.model.transcribe(
whisper  |   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/whisper/transcribe.py", line 237, in transcribe
whisper  |     mel_segment = pad_or_trim(mel_segment, N_FRAMES).to(model.device).to(dtype)
whisper  | RuntimeError: HIP error: the operation cannot be performed in the present state
whisper  | HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
whisper  | For debugging consider passing HIP_LAUNCH_BLOCKING=1.
whisper  | Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
whisper  |_ 

**amdgpu_top:**
![image](https://github.com/user-attachments/assets/44c96905-3f4f-4483-bb8d-560394fe1fc3)

**My docker-compose.yaml**:
```yaml
services:
  whisper:
    container_name: whisper
    restart: unless-stopped
    build:
      context: .
    group_add:
      - video
    volumes:
      - /home/whipser/data:/data
    command:
      - --download-dir
      - /data
      - --language
      - pl
      - --device
      - cuda
    ports:
      - 10300:10300
    devices:
      - "/dev/dri"
      - "/dev/kfd"
    environment:
      - HSA_OVERRIDE_GFX_VERSION=9.0.0
      - PYTORCH_ROCM_ARCH='gfx900'
      - ROCR_VISIBLE_DEVICES=GPU-021515832a5840c4
      - HIP_VISIBLE_DEVICES=0
    security_opt:
      - seccomp:unconfined
```
Nothing else has been modified. Any clues?
